### ISSUE TITLE
How to customize and run invoiced php version?

### ISSUE THREAD

**Issue by iampriyatam** [wotta/Invoiced#4]
I am trying to run it on my localhost. But getting error, i also installed composer but not worked for me. Please help me step by step if possible.

**Comment by iampriyatam** [comment]
![image](https://user-images.githubusercontent.com/12632211/46074815-43bd2000-c1a6-11e8-876c-d80701bd9d1e.png)

**Comment by wotta** [comment]
That's the error that you get when you don't run composer install.
Please run composer install in your application folder.

**Comment by iampriyatam** [comment]
![image](https://user-images.githubusercontent.com/12632211/46092039-98c25b80-c1d1-11e8-9140-557d7fdf8451.png)

**Comment by iampriyatam** [comment]
now i am getting this after installing composer

**Comment by wotta** [comment]
Well I have never seen that error since I don't use Windows with edge.

I cannot help you with that.
Also note that when I said you should run composer install, you told me that you done that.
Afterwards you show me you got the error because no composer install was run.

Debug how far the application comes to figure out what's wrong.

I am not going to help any further in this matter.
